version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: task-postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - task-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-app
    restart: always
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: taskdb
      JWT_SECRET: secret-key-1234
      PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - task-network

networks:
  task-network:
    driver: bridge

volumes:
  postgres_data: